apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2020-10-22T16:22:25Z'
  generation: 6
  labels:
    app: uam-api
  name: uam-api
  namespace: ruby-uam-uat
  resourceVersion: '171329538'
  selfLink: /apis/apps.openshift.io/v1/namespaces/ruby-uam-uat/deploymentconfigs/uam-api
  uid: c566c22d-1482-11eb-bee5-4cd98f45507b
spec:
  replicas: 1
  selector:
    deploymentconfig: uam-api
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uam-api
        deploymentconfig: uam-api
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/ruby-uam-uat/uam-api@sha256:d97b68e3083d7d9514e234e8423b6d5f5c0f0eaae9192ef01d48b6045e3896b9
          imagePullPolicy: Always
          name: uam-api
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - uam-api
        from:
          kind: ImageStreamTag
          name: 'uam-api:latest'
          namespace: ruby-uam-uat
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/ruby-uam-uat/uam-api@sha256:d97b68e3083d7d9514e234e8423b6d5f5c0f0eaae9192ef01d48b6045e3896b9
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-14T02:33:01Z'
      lastUpdateTime: '2020-12-14T02:33:05Z'
      message: replication controller "uam-api-5" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2020-12-18T02:35:22Z'
      lastUpdateTime: '2020-12-18T02:35:22Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/ruby-uam-uat/uam-api@sha256:d97b68e3083d7d9514e234e8423b6d5f5c0f0eaae9192ef01d48b6045e3896b9
        type: ImageChange
    message: image change
  latestVersion: 5
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
